// This file is autogenerated. Changes will be overwritten.
#include "JH45IGJHDZ/moc_file_manager.cpp"
#include "JH45IGJHDZ/moc_twitch_api_client.cpp"
#include "JH45IGJHDZ/moc_twitch_authenticator.cpp"
#include "TAC5DWH4SE/moc_app_controller.cpp"
#include "UYX5XTB5RZ/moc_mainwindow.cpp"
